client_id = "276eebefa8668fd34d829854ade20e31"
name = "COGS Margin Tracker"
application_url = "https://cogs.leverageapps.co"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
scopes = "read_products,write_products,read_orders,read_inventory,write_inventory"

[billing]
  [billing.cogs_tracker_plan]
  amount = 9.99
  currency_code = "USD"
  interval = "EVERY_30_DAYS"
  trial_days = 7

[auth]
redirect_urls = [ "https://cogs.leverageapps.co/auth/callback" ]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = ["products/update"]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = ["inventory_items/update"]
  uri = "/webhooks/inventory-items/update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = ["customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = ["shop/redact"]
